CONTROLLER_HEART_BEAT_EXPIRATION = 30
WORKER_HEART_BEAT_INTERVAL = 15

LOGDIR = "."

# Model Constants
IGNORE_INDEX = -100
IMAGE_TOKEN_INDEX = -200
DEFAULT_IMAGE_TOKEN = "<image>"
DEFAULT_IMAGE_PATCH_TOKEN = "<im_patch>"
DEFAULT_IM_START_TOKEN = "<im_start>"
DEFAULT_IM_END_TOKEN = "<im_end>"
QWEN_IGNORE_INDEX = 151643 # '<|endoftext|>'


# len(COCO_80_CATEGORY) = 80
COCO_80_CATEGORY = ['person', 'bicycle', 'car', 'motorcycle', 'airplane', 'bus', 'train', 
'truck', 'boat', 'traffic light', 'fire hydrant', 'stop sign', 
'parking meter', 'bench', 'bird', 'cat', 'dog', 'horse', 'sheep', 
'cow', 'elephant', 'bear', 'zebra', 'giraffe', 'backpack', 'umbrella', 
'handbag', 'tie', 'suitcase', 'frisbee', 'skis', 'snowboard', 'sports ball', 
'kite', 'baseball bat', 'baseball glove', 'skateboard', 'surfboard', 
'tennis racket', 'bottle', 'wine glass', 'cup', 'fork', 'knife', 'spoon', 
'bowl', 'banana', 'apple', 'sandwich', 'orange', 'broccoli', 'carrot', 
'hot dog', 'pizza', 'donut', 'cake', 'chair', 'couch', 'potted plant', 
'bed', 'dining table', 'toilet', 'tv', 'laptop', 'mouse', 'remote', 
'keyboard', 'cell phone', 'microwave', 'oven', 'toaster', 'sink', 
'refrigerator', 'book', 'clock', 'vase', 'scissors', 'teddy bear', 
'hair drier', 'toothbrush']


# len(OBJECTS365_CLASS_NAMES) = 365
OBJECTS365_CLASS_NAMES = [
    "person",
    "sneakers",
    "chair",
    "other shoes",
    "hat",
    "car",
    "lamp",
    "glasses",
    "bottle",
    "desk",
    "cup",
    "street lights",
    "cabinet (shelf)",
    "handbag (satchel)",
    "bracelet",
    "plate",
    "picture (frame)",
    "helmet",
    "book",
    "gloves",
    "storage box",
    "boat",
    "leather shoes",
    "flower",
    "bench",
    "potted plant",
    "bowl (basin)",
    "flag",
    "pillow",
    "boots",
    "vase",
    "microphone",
    "necklace",
    "ring",
    "suv",
    "wine glass",
    "belt",
    "monitor (tv)",
    "backpack",
    "umbrella",
    "traffic light",
    "speaker",
    "watch",
    "tie",
    "trash bin can",
    "slippers",
    "bicycle",
    "stool",
    "barrel (bucket)",
    "van",
    "couch",
    "sandals",
    "basket",
    "drum",
    "pen (pencil)",
    "bus",
    "wild bird",
    "high heels",
    "motorcycle",
    "guitar",
    "carpet",
    "cell phone",
    "bread",
    "camera",
    "canned",
    "truck",
    "traffic cone",
    "cymbal",
    "lifesaver",
    "towel",
    "stuffed toy",
    "candle",
    "sailboat",
    "laptop",
    "awning",
    "bed",
    "faucet",
    "tent",
    "horse",
    "mirror",
    "power outlet",
    "sink",
    "apple",
    "air conditioner",
    "knife",
    "hockey stick",
    "paddle",
    "pickup truck",
    "fork",
    "traffic sign",
    "balloon",
    "tripod",
    "dog",
    "spoon",
    "clock",
    "pot",
    "cow",
    "cake",
    "dinning table",
    "sheep",
    "hanger",
    "blackboard (whiteboard)",
    "napkin",
    "other fish",
    "orange (tangerine)",
    "toiletry",
    "keyboard",
    "tomato",
    "lantern",
    "machinery vehicle",
    "fan",
    "green vegetables",
    "banana",
    "baseball glove",
    "airplane",
    "mouse",
    "train",
    "pumpkin",
    "soccer",
    "skiboard",
    "luggage",
    "nightstand",
    "tea pot",
    "telephone",
    "trolley",
    "head phone",
    "sports car",
    "stop sign",
    "dessert",
    "scooter",
    "stroller",
    "crane",
    "remote",
    "refrigerator",
    "oven",
    "lemon",
    "duck",
    "baseball bat",
    "surveillance camera",
    "cat",
    "jug",
    "broccoli",
    "piano",
    "pizza",
    "elephant",
    "skateboard",
    "surfboard",
    "gun",
    "skating and skiing shoes",
    "gas stove",
    "donut",
    "bow tie",
    "carrot",
    "toilet",
    "kite",
    "strawberry",
    "other balls",
    "shovel",
    "pepper",
    "computer box",
    "toilet paper",
    "cleaning products",
    "chopsticks",
    "microwave",
    "pigeon",
    "baseball",
    "cutting (chopping board)",
    "coffee table",
    "side table",
    "scissors",
    "marker",
    "pie",
    "ladder",
    "snowboard",
    "cookies",
    "radiator",
    "fire hydrant",
    "basketball",
    "zebra",
    "grape",
    "giraffe",
    "potato",
    "sausage",
    "tricycle",
    "violin",
    "egg",
    "fire extinguisher",
    "candy",
    "fire truck",
    "billiards",
    "converter",
    "bathtub",
    "wheelchair",
    "golf club",
    "briefcase",
    "cucumber",
    "cigar (cigarette)",
    "paint brush",
    "pear",
    "heavy truck",
    "hamburger",
    "extractor",
    "extension cord",
    "tong",
    "tennis racket",
    "folder",
    "american football",
    "earphone",
    "mask",
    "kettle",
    "tennis",
    "ship",
    "swing",
    "coffee machine",
    "slide",
    "carriage",
    "onion",
    "green beans",
    "projector",
    "frisbee",
    "washing machine (drying machine)",
    "chicken",
    "printer",
    "watermelon",
    "saxophone",
    "tissue",
    "toothbrush",
    "ice cream",
    "hot-air balloon",
    "cello",
    "french fries",
    "scale",
    "trophy",
    "cabbage",
    "hot dog",
    "blender",
    "peach",
    "rice",
    "wallet (purse)",
    "volleyball",
    "deer",
    "goose",
    "tape",
    "tablet",
    "cosmetics",
    "trumpet",
    "pineapple",
    "golf ball",
    "ambulance",
    "parking meter",
    "mango",
    "key",
    "hurdle",
    "fishing rod",
    "medal",
    "flute",
    "brush",
    "penguin",
    "megaphone",
    "corn",
    "lettuce",
    "garlic",
    "swan",
    "helicopter",
    "green onion",
    "sandwich",
    "nuts",
    "speed limit sign",
    "induction cooker",
    "broom",
    "trombone",
    "plum",
    "rickshaw",
    "goldfish",
    "kiwi fruit",
    "router (modem)",
    "poker card",
    "toaster",
    "shrimp",
    "sushi",
    "cheese",
    "notepaper",
    "cherry",
    "pliers",
    "cd",
    "pasta",
    "hammer",
    "cue",
    "avocado",
    "hamimelon",
    "flask",
    "mushroom",
    "screwdriver",
    "soap",
    "recorder",
    "bear",
    "eggplant",
    "board eraser",
    "coconut",
    "tape measure (ruler)",
    "pig",
    "showerhead",
    "globe",
    "chips",
    "steak",
    "crosswalk sign",
    "stapler",
    "camel",
    "formula 1",
    "pomegranate",
    "dishwasher",
    "crab",
    "hoverboard",
    "meat ball",
    "rice cooker",
    "tuba",
    "calculator",
    "papaya",
    "antelope",
    "parrot",
    "seal",
    "butterfly",
    "dumbbell",
    "donkey",
    "lion",
    "urinal",
    "dolphin",
    "electric drill",
    "hair dryer",
    "egg tart",
    "jellyfish",
    "treadmill",
    "lighter",
    "grapefruit",
    "game board",
    "mop",
    "radish",
    "baozi",
    "target",
    "french",
    "spring rolls",
    "monkey",
    "rabbit",
    "pencil case",
    "yak",
    "red cabbage",
    "binoculars",
    "asparagus",
    "barbell",
    "scallop",
    "noddles",
    "comb",
    "dumpling",
    "oyster",
    "table tennis paddle",
    "cosmetics brush (eyeliner pencil)",
    "chainsaw",
    "eraser",
    "lobster",
    "durian",
    "okra",
    "lipstick",
    "cosmetics mirror",
    "curling",
    "table tennis",
]
